name: jcr
on:
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-jcr
  schedule:
    - cron: '0 * * * *'
jobs:
  run:
    services:
      jcr:
        image: docker.bintray.io/jfrog/artifactory-jcr:latest
        ports:
          - 8081:8081
          - 8082:8082
    runs-on: ubuntu-latest
    steps:
      # Not working. Immediately fails
      - name: Wait for JCR to be ready
        uses: maddox/actions/wait-for-200@master
        env:
            URL: http://jcr:${{ job.services.jcr.ports['8081'] }}/artifactory/api/system/ping
            # URL: http://localhost:${{ job.services.jcr.ports['8081'] }}/artifactory/api/system/ping
            SECONDS_BETWEEN_CHECKS: 5
            MAX_TRIES: 20
      # - name: Sleep for 80 seconds. Allow JCR to finish startup.
      #   uses: jakejarvis/wait-action@master
      #   with:
      #     time: '80s'
      - name: Checkout Workspace
        uses: actions/checkout@v2
      - name: Apply conformance config to JCR
        run: curl -u admin:password -X POST -H "Content-type:application/xml" --data-binary "@$GITHUB_WORKSPACE/configurations/jcr/artifactory.config.import.xml"  http://localhost:${{ job.services.jcr.ports['8081'] }}/artifactory/api/system/configuration
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@master
        env:
          OCI_ROOT_URL: http://jcr:8081
          OCI_NAMESPACE: conformance-local/oci-conformance-test
          OCI_USERNAME: ${{ secrets.JCR_USERNAME }}
          OCI_PASSWORD: ${{ secrets.JCR_PASSWORD }}
          # OCI_DEBUG: true
      # - name: Upload test report to S3
      #   run: aws s3 cp --acl public-read report.html s3://oci-distribution-conformance-results/distribution.html
      #   if: always()
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
